# Generated by Django 3.1.7 on 2021-10-26 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_name', models.CharField(max_length=150, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(blank=True, max_length=12, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, max_length=150, verbose_name='Город')),
                ('region', models.CharField(blank=True, max_length=150, verbose_name='Область')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_access', models.BooleanField(verbose_name='Есть ли доступ к курсу')),
                ('is_passed', models.BooleanField(verbose_name='Пройден ли курс')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileLearning.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
