# Generated by Django 3.1.7 on 2021-11-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileLearning', '0005_auto_20211127_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='second_name',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Отчество'),
        ),
    ]
