# Generated by Django 3.1.7 on 2021-11-27 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileLearning', '0012_auto_20211127_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date(1, 1, 1), verbose_name='Дата рождения'),
        ),
    ]
