# Generated by Django 3.1.7 on 2021-11-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileLearning', '0013_auto_20211127_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='images',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Фото'),
        ),
    ]
