# Generated by Django 3.1.7 on 2021-12-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileLearning', '0014_profile_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscourse',
            name='test_status',
            field=models.CharField(default='не начат', max_length=20, verbose_name='Статус теста'),
        ),
    ]
