# Generated by Django 3.1.7 on 2021-12-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileLearning', '0020_auto_20211209_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='images',
            field=models.ImageField(default='Non', upload_to='media/', verbose_name='Фото'),
        ),
    ]
