# Generated by Django 3.1.7 on 2021-12-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileLearning', '0021_auto_20211209_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='images',
            field=models.ImageField(default='None', upload_to='media/', verbose_name='Фото'),
        ),
    ]
