# Generated by Django 3.1.7 on 2021-12-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileLearning', '0024_auto_20211211_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscourse',
            name='right_answers',
            field=models.CharField(default='', max_length=50, verbose_name='Правильные варианты ответа'),
        ),
        migrations.AddField(
            model_name='accesscourse',
            name='wrong_answers',
            field=models.CharField(default='', max_length=50, verbose_name='Неправильные варианты ответа'),
        ),
    ]
