# Generated by Django 3.1.7 on 2021-12-14 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileLearning', '0026_auto_20211212_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.CharField(default='', max_length=200, verbose_name='Фото курса'),
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.CharField(default='', max_length=20, verbose_name='Время прохождения'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 12, 14, 13, 22, 43, 331259), verbose_name='Дата рождения'),
        ),
    ]
