# Generated by Django 3.1.7 on 2021-12-14 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileLearning', '0027_auto_20211214_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='start_course',
            field=models.CharField(default='', max_length=50, verbose_name='Ссылка на старт курса'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 12, 14, 13, 59, 56, 242680), verbose_name='Дата рождения'),
        ),
    ]
