# Generated by Django 3.1.7 on 2021-12-14 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileLearning', '0028_auto_20211214_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Название курса')),
                ('image', models.CharField(default='', max_length=200, verbose_name='Фото курса')),
                ('time', models.CharField(default='', max_length=20, verbose_name='Время прохождения')),
                ('start_lection', models.CharField(default='', max_length=50, verbose_name='Ссылка на старт курса')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 12, 14, 14, 28, 11, 582558), verbose_name='Дата рождения'),
        ),
    ]
