# Generated by Django 3.1.7 on 2021-12-19 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileLearning', '0030_auto_20211218_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='direction',
            field=models.CharField(default='ALL', max_length=50, verbose_name='Направление подготовки'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 12, 19, 9, 42, 47, 945288), verbose_name='Дата рождения'),
        ),
    ]
